[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
prediction_market = "4g6WvpafKJy1kbJjtA1zkusnqcMbCFiF7fdnDKZW6jZk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
